---
apiVersion: v1
kind: ConfigMap
metadata:
  name: singlelog-count-cm
data:
  singlelog_count.yaml: |-
    ---
    period: {{.Values.singlelog_count.period}}
    offset: {{.Values.singlelog_count.offset}}
    countersfile: {{.Values.singlelog_count.countersfile | quote}}
    redis_pub_channel: {{.Values.singlelog_count.redis_pub_channel | quote}}
    redis_host: {{.Values.redis.host | quote}}
    redis_port: {{.Values.redis.port}}
    redis_db: {{.Values.redis.db}}
  {{- $root := "files/singlelog-count"}}
  counters_list: {{$.Files.Get (print $root "/counters_list") | quote}}
  {{- range $path, $bytes := .Files.Glob "files/singlelog-count/**.json"}}
  counters_{{base $path}}: {{$.Files.Get $path | quote}}
  {{- end}}
